
version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
      day: 'monday' # Choose a specific day of the week (e.g., 'monday')
      time: '10:00'
    open-pull-requests-limit: 10
